version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - errcheck
    - gosec
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unused
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
  settings:
    revive:
      rules:
        - name: var-naming
          severity: warning
          disabled: false
          exclude: [ "" ]
          arguments:
            - [ "ID" ] # AllowList
            - [ "VM" ] # DenyList
            - - skip-initialism-name-checks: true
                upper-case-const: true
                skip-package-name-checks: true
                skip-package-name-collision-with-go-std: true
                extra-bad-package-names:
                  - helpers
                  - models
formatters:
  enable:
    - gci
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
